### ISSUE TITLE
Issue forbidding importing any submodule with wildcard

### ISSUE THREAD

**Issue by jordanhamill** [seddonym/import-linter#125] opened 2022-06-21 13:41 UTC
I have a `common` module that shouldn't import anything else (avoiding circular imports).

I initially tried this with the `forbidden` contract and wildcard but it does not work. It will work if I type out every submodule, how that is brittle when other developers add a new module or package.

```toml
[[tool.importlinter.contracts]]
name = "app.common cannot import any other modules"
type = "forbidden"
source_modules = [
    "app.common",
]
forbidden_modules = [
    "app.*"
]
```

A quick dig through the code shows the issue here.
```py
 # We only need to check for illegal imports for forbidden modules that are in the graph.
forbidden_modules_in_graph = [m for m in self.forbidden_modules if m.name in graph.modules]  # type: ignore
```

`m.name` is `app.*` which wont match. I could hack something in but there seems to be some partial wildcard support already and not sure if there's anything for matching already.

**Comment by seddonym** [comment] 2022-06-22 11:35
Thanks for raising this!

I think it's a duplicate of https://github.com/seddonym/import-linter/issues/56 - could you confirm?

**Comment by jordanhamill** [comment] 2022-06-22 11:44
Yes that looks like it would cover this issue!

**Closed** 2022-06-22 11:57 UTC
